import { StyleSheet } from 'react-native';
import { ANDROID_STATUS_BAR } from '../config/constants';

const commonStyles = StyleSheet.create({
  rootContainer: { flex: 1, backgroundColor: '#0f172a' },
  header: {
    backgroundColor: '#166534',
    paddingTop: ANDROID_STATUS_BAR + 10,
    paddingBottom: 12,
    paddingHorizontal: 14,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4
  },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  shopInfo: { flexDirection: 'row', alignItems: 'center', gap: 8, flex: 1 },
  shopIcon: { fontSize: 22, backgroundColor: '#15803d', padding: 4, borderRadius: 8 },
  shopName: { color: '#fff', fontWeight: '800', fontSize: 16 },
  shopSub: { color: '#bbf7d0', fontSize: 10.5 },
  langToggleBtn: {
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderWidth: 1,
    borderColor: '#86efac',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4
  },
  langToggleText: { color: '#ffffff', fontSize: 10, fontWeight: 'bold' },
  gstBadge: {
    backgroundColor: 'rgba(5, 46, 22, 0.8)',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#15803d'
  },
  gstText: { color: '#86efac', fontSize: 9, fontWeight: '700' },
  contentScroll: { flex: 1, backgroundColor: '#f1f5f9' },
  contentInner: { padding: 10, paddingBottom: 110 },
  tabSection: { gap: 10 },
  editModeBanner: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#fef3c7',
    borderWidth: 1,
    borderColor: '#fde68a',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8
  },
  editModeText: { color: '#92400e', fontWeight: 'bold', fontSize: 12 },
  cancelEditBtn: { backgroundColor: '#dc2626', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 4 },
  cancelEditText: { color: '#fff', fontSize: 11, fontWeight: 'bold' },
  modeContainer: { flexDirection: 'row', backgroundColor: '#fff', padding: 4, borderRadius: 12, gap: 6 },
  modeBtn: { flex: 1, paddingVertical: 10, borderRadius: 8, alignItems: 'center' },
  modeBtnActiveCash: { backgroundColor: '#166534' },
  modeBtnActiveCredit: { backgroundColor: '#b91c1c' },
  modeBtnText: { fontSize: 13, fontWeight: '700', color: '#475569' },
  modeBtnTextActive: { color: '#fff' },
  card: { backgroundColor: '#fff', padding: 12, borderRadius: 14, borderWidth: 1, borderColor: '#e2e8f0' },
  cardLabel: { fontSize: 14, fontWeight: '800', color: '#1e293b', marginBottom: 8 },
  searchInput: {
    borderWidth: 1.5,
    borderColor: '#16a34a',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    fontWeight: '600',
    color: '#0f172a',
    backgroundColor: '#fff'
  },
  dropdown: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 10,
    marginTop: 4,
    overflow: 'hidden'
  },
  cleanDropdownItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9'
  },
  dropTitle: { fontSize: 13, fontWeight: '700', color: '#0f172a' },
  dropSub: { fontSize: 10.5, color: '#64748b' },
  dropPrice: {
    fontSize: 13,
    fontWeight: '700',
    color: '#166534',
    backgroundColor: '#f0fdf4',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4
  },
  stockPill: {
    paddingHorizontal: 6,
    paddingVertical: 1.5,
    borderRadius: 6,
    borderWidth: 1
  },
  stockPillGreen: { backgroundColor: '#f0fdf4', borderColor: '#bbf7d0' },
  stockPillYellow: { backgroundColor: '#fffbeb', borderColor: '#fde68a' },
  stockPillRed: { backgroundColor: '#fef2f2', borderColor: '#fecaca' },
  stockPillText: { fontSize: 9.5, fontWeight: 'bold' },
  stockTextGreen: { color: '#166534' },
  stockTextYellow: { color: '#b45309' },
  stockTextRed: { color: '#dc2626' },
  customerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
    paddingBottom: 4
  },
  transliterateHint: {
    fontSize: 11,
    color: '#15803d',
    fontWeight: '700',
    marginBottom: 8,
    backgroundColor: '#f0fdf4',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    alignSelf: 'flex-start'
  },
  billBadge: {
    backgroundColor: '#f0fdf4',
    borderColor: '#bbf7d0',
    borderWidth: 1,
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 4
  },
  billBadgeText: { fontSize: 10.5, fontWeight: 'bold', color: '#166534' },
  editLink: { fontSize: 11.5, color: '#2563eb', fontWeight: '700' },
  resetBtn: {
    backgroundColor: '#eff6ff',
    borderColor: '#bfdbfe',
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6
  },
  resetBtnText: { fontSize: 11.5, color: '#1d4ed8', fontWeight: 'bold' },
  row: { flexDirection: 'row', gap: 8 },
  input: {
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 13.5,
    color: '#0f172a',
    backgroundColor: '#fff'
  },
  cartHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  clearCartText: { color: '#dc2626', fontSize: 12, fontWeight: '600' },
  emptyCartText: { textAlign: 'center', color: '#94a3b8', fontSize: 12, marginVertical: 14 },
  cartRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#f8fafc'
  },
  cartItemTitle: { fontSize: 12.5, fontWeight: '700', color: '#0f172a' },
  cartItemSub: { fontSize: 10, color: '#94a3b8' },
  stepper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 6,
    overflow: 'hidden'
  },
  stepBtn: { backgroundColor: '#f1f5f9', paddingHorizontal: 7, paddingVertical: 3 },
  stepBtnText: { fontSize: 13, fontWeight: 'bold' },
  stepQty: { width: 24, textAlign: 'center', fontSize: 12, fontWeight: 'bold' },
  rateInput: {
    width: 52,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 4,
    textAlign: 'center',
    fontSize: 12,
    fontWeight: 'bold',
    backgroundColor: '#fffbeb',
    paddingVertical: 3
  },
  lineTotal: { width: 54, textAlign: 'right', fontSize: 12.5, fontWeight: 'bold', color: '#0f172a' },
  delBtn: { color: '#ef4444', fontWeight: 'bold', paddingHorizontal: 4 },
  calcRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 3 },
  calcLabel: { fontSize: 13, color: '#475569', fontWeight: '600' },
  calcVal: { fontSize: 14, fontWeight: '800', color: '#0f172a' },
  grandLabel: { fontSize: 16, fontWeight: '900', color: '#0f172a' },
  grandVal: { fontSize: 18, fontWeight: '900', color: '#166534' },
  dueLabel: { fontSize: 13.5, fontWeight: '800', color: '#dc2626' },
  dueVal: { fontSize: 15, fontWeight: '900', color: '#dc2626' },
  discInput: {
    width: 95,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 8,
    textAlign: 'right',
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: 13.5,
    fontWeight: '700'
  },
  cashPaidBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: '#f0fdf4',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#bbf7d0'
  },
  cashPaidText: { fontSize: 13, fontWeight: 'bold', color: '#166534' },
  paidInput: {
    width: 105,
    borderWidth: 1.5,
    borderColor: '#16a34a',
    backgroundColor: '#f0fdf4',
    borderRadius: 8,
    textAlign: 'right',
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: 14,
    fontWeight: '800',
    color: '#166534'
  },
  totalDivider: { borderTopWidth: 1, borderTopColor: '#f1f5f9', paddingTop: 6 },
  submitBtn: {
    backgroundColor: '#166534',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 6
  },
  submitBtnText: { color: '#fff', fontSize: 14, fontWeight: '800' },
  dailyDashboardCard: {
    backgroundColor: '#0f172a',
    borderRadius: 14,
    padding: 12,
    marginBottom: 4
  },
  dailyDashboardTitle: { fontSize: 12, fontWeight: 'bold', color: '#94a3b8', marginBottom: 8, textAlign: 'center' },
  dailyDashboardRow: { flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center' },
  dailyDashLabel: { fontSize: 10, color: '#cbd5e1' },
  dailyDashValTotal: { fontSize: 14, fontWeight: '900', color: '#38bdf8', marginTop: 2 },
  dailyDashValCash: { fontSize: 14, fontWeight: '900', color: '#4ade80', marginTop: 2 },
  dailyDashValDue: { fontSize: 14, fontWeight: '900', color: '#f87171', marginTop: 2 },
  sectionHeading: { fontSize: 13.5, fontWeight: '800', color: '#1e293b' },
  historySearchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    paddingHorizontal: 10
  },
  historySearchInput: { flex: 1, paddingVertical: 8, fontSize: 13, color: '#0f172a' },
  clearSearchBtn: { padding: 4 },
  fetchBillsBtn: {
    backgroundColor: '#166534',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
    flexDirection: 'row',
    alignItems: 'center'
  },
  fetchBillsBtnText: { color: '#fff', fontSize: 11, fontWeight: 'bold' },
  fetchProductsBtn: {
    backgroundColor: '#166534',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
    flexDirection: 'row',
    alignItems: 'center'
  },
  fetchProductsBtnText: { color: '#fff', fontSize: 11, fontWeight: 'bold' },
  prodCountBadge: {
    backgroundColor: '#dcfce7',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#86efac'
  },
  prodCountBadgeText: { fontSize: 11, fontWeight: '800', color: '#166534' },
  bottomNav: {
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    paddingTop: 8,
    paddingBottom: 20,
    minHeight: 68,
    alignItems: 'center',
    elevation: 12,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 4
  },
  navItem: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 2 },
  navIcon: { fontSize: 18 },
  navText: { fontSize: 11.5, fontWeight: '700', color: '#64748b' },
  navTextActive: { color: '#166534', fontWeight: '800' },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16
  },
  modalCard: { backgroundColor: '#fff', borderRadius: 16, padding: 14, width: '100%', maxWidth: 360 },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
    paddingBottom: 8,
    marginBottom: 8
  },
  formLabel: { fontSize: 11.5, fontWeight: 'bold', color: '#334155', marginTop: 4 },
  formInput: {
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
    fontSize: 13,
    color: '#0f172a'
  },
  saveProdSubmitBtn: {
    backgroundColor: '#166534',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 10
  },
  saveProdSubmitBtnText: { color: '#fff', fontSize: 13, fontWeight: 'bold' },
  bulkHelperBox: {
    backgroundColor: '#f8fafc',
    padding: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    marginBottom: 8
  },
  bulkHelperTitle: { fontSize: 11, fontWeight: 'bold', color: '#166534' },
  bulkHelperText: { fontSize: 10, color: '#64748b', marginTop: 1 },
  bulkTextArea: {
    borderWidth: 1.5,
    borderColor: '#cbd5e1',
    borderRadius: 8,
    padding: 10,
    fontSize: 12,
    color: '#0f172a',
    backgroundColor: '#fff',
    minHeight: 120
  },
  customDialogBox: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 20,
    width: '100%',
    maxWidth: 320,
    alignItems: 'center',
    elevation: 8
  },
  dialogIconCircle: {
    width: 54,
    height: 54,
    borderRadius: 27,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12
  },
  dialogIconPrimary: { backgroundColor: '#f0fdf4' },
  dialogIconDanger: { backgroundColor: '#fef2f2' },
  dialogTitleText: { fontSize: 16, fontWeight: '800', color: '#0f172a', marginBottom: 6, textAlign: 'center' },
  dialogMsgText: { fontSize: 12, color: '#475569', textAlign: 'center', lineHeight: 18, marginBottom: 18 },
  dialogActionsRow: { flexDirection: 'row', gap: 10, width: '100%' },
  dialogBtn: { flex: 1, paddingVertical: 10, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  dialogCancelBtn: { backgroundColor: '#f1f5f9' },
  dialogCancelText: { fontSize: 12, fontWeight: 'bold', color: '#475569' },
  dialogConfirmBtn: { backgroundColor: '#166534' },
  dialogDestructiveBtn: { backgroundColor: '#dc2626' },
  dialogConfirmText: { fontSize: 12, fontWeight: 'bold', color: '#ffffff' },
  toastContainer: {
    position: 'absolute',
    top: ANDROID_STATUS_BAR + 50,
    left: 16,
    right: 16,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    elevation: 8,
    zIndex: 9999
  },
  toastSuccess: { backgroundColor: '#14532d' },
  toastError: { backgroundColor: '#991b1b' },
  toastInfo: { backgroundColor: '#0f172a' },
  toastIconText: { fontSize: 14 },
  toastMsgText: { color: '#ffffff', fontSize: 12, fontWeight: '700', flex: 1 }
});

export default commonStyles;
