const STRINGS = {
  hi: {
    shopName: 'जीवन कृषि केन्द्र',
    shopSub: 'ग्राम देवरी, धमतरी (छ.ग.)',
    billingTab: 'बिलिंग',
    searchTab: 'रोग खोज',
    cementTab: 'सीमेंट',
    stagesTab: 'फसल गाइड',
    historyTab: 'इतिहास',
    cashBill: '💵 नकद बिल (Cash)',
    creditBill: '📋 उधार बिल (Credit)',
    searchProductPlaceholder: 'दवा, सीमेंट या रोग खोजें (उदा. coragen, cement)...',
    farmerDetails: 'किसान विवरण',
    farmerName: 'किसान का नाम *',
    fatherName: 'पिता का नाम (वैकल्पिक)',
    village: 'गाँव',
    phone: 'मोबाइल नंबर (10 अंक)',
    cartItems: '🛒 बिल में सामान',
    emptyCart: "बिल में अभी कोई सामान नहीं है। ऊपर से खोजें या 'रोग खोज' टैब से जोड़ें।",
    emptyBillError: 'बिल में कम से कम 1 सामान अवश्य जोड़ें!',
    billItemsLabel: 'सामान का विवरण',
    emptyInvoiceItems: 'वस्तुओं की विस्तृत सूची उपलब्ध नहीं है',
    subtotal: 'उप-योग (Subtotal):',
    discount: 'छूट (Discount ₹):',
    grandTotal: 'कुल रकम (Grand Total):',
    paid: 'जमा राशि (Paid):',
    due: 'शेष उधार (Balance Due):',
    saveBill: '🖨️ प्रमाणित बिल सेव करें (Drive Sync)',
    updateBill: '💾 अपडेट करें एवं पर्ची देखें',
    availableMedicines: '📦 उपलब्ध दवाइयां',
    syncMedicines: '🔄 सिंक दवाइयां',
    singleAdd: '➕ सिंगल',
    bulkAdd: '📦 बल्क जोड़ें',
    allPests: 'सभी',
    lowStockChip: '⚠️ कम स्टॉक',
    oldBills: '📜 पुराने बिल इतिहास',
    syncHistory: '🔄 सिंक इतिहास',
    receipt: 'रसीद',
    edit: '✏️ एडिट',
    pdf: '🖨️ PDF',
    whatsapp: '💬 WA',
    newBill: '🔄 नया बिल',
    change: '✏️ बदलें',
    outOfStockBadge: '🔴 स्टॉक खत्म',
    lowStockBadge: '⚠ कम स्टॉक',
    dosePerAcreLabel: 'प्रति एकड़',
    drumDoseLabel: '200L ड्रम',
    pumpDoseLabel: 'प्रति 15L पंप',
    cementTitle: '🏗️ सीमेंट व बिल्डिंग सामग्री',
    cementSubtitle: 'सभी उपलब्ध सीमेंट प्रोडक्ट्स',
    cementSearchPlaceholder: 'ब्रांड, कंपनी या ग्रेड खोजें...',
    cementAllBrands: 'सभी ब्रांड',
    cementLowStockOnly: '⚠️ कम स्टॉक',
    cementSync: 'सिंक',
    cementSyncPending: 'सीमेंट स्थानीय रूप से सेव है; शीट सिंक लंबित है।',
    cementAdd: '➕ सीमेंट जोड़ें',
    cementAddToBill: '➕ बिल में जोड़ें',
    cementOutOfStock: '🔴 स्टॉक खत्म',
    cementLowStock: '⚠️ कम स्टॉक',
    cementBagStockCount: 'स्टॉक: {count} बैग',
    cementBagUnit: 'बैग',
    cementInStock: 'बैग उपलब्ध',
    cementStockAdjustment: 'स्टॉक समायोजन',
    cementNoItems: 'सीमेंट उपलब्ध नहीं है',
    cementEdit: '✏️ एडिट',
    cementDelete: '🗑 हटाएं',
    cementDeleteTitle: 'सीमेंट हटाएं?',
    cementDeleteMessage: 'क्या आप वाकई "{brand}" को सूची से हटाना चाहते हैं?',
    cementAddTitle: 'नया सीमेंट जोड़ें',
    cementEditTitle: 'सीमेंट एडिट करें',
    cementBrand: 'ब्रांड *',
    cementCompany: 'कंपनी *',
    cementGrade: 'ग्रेड *',
    cementBagWeight: 'बैग वजन *',
    cementCashPrice: 'नकद मूल्य / बैग *',
    cementCreditPrice: 'उधार मूल्य / बैग *',
    cementCashLabel: 'नकद',
    cementCreditLabel: 'उधार',
    cementStockError: 'स्टॉक में केवल {count} बैग उपलब्ध हैं।',
    cementStock: 'स्टॉक (बैग) *',
    cementBrandPlaceholder: 'उदा. UltraTech Cement',
    cementCompanyPlaceholder: 'उदा. UltraTech',
    cementBagWeightPlaceholder: 'उदा. 50 kg',
    cementBatchOptional: 'बैच (वैकल्पिक)',
    cementExpiryOptional: 'एक्सपायरी (वैकल्पिक)',
    cementRequired: 'यह जानकारी आवश्यक है',
    cementInvalidNumber: 'शून्य या उससे अधिक संख्या दर्ज करें',
    cementSave: 'सीमेंट सेव करें',
    cementSaveChanges: 'बदलाव सुरक्षित करें',
    cementAddedToBill: 'सीमेंट बिल में जोड़ा गया।',
    cementAdded: 'सीमेंट स्थानीय सूची में जोड़ा गया।',
    cementUpdated: 'सीमेंट जानकारी अपडेट हुई।',
    cementDeleted: 'सीमेंट सूची से हटाया गया।'
  },
  en: {
    shopName: 'Jeevan Krishi Kendra',
    shopSub: 'Vill - Devri, Dhamtari (C.G.) | 70891-01502',
    billingTab: 'Billing',
    searchTab: 'Pest Search',
    cementTab: 'Cement',
    stagesTab: 'Crop Guide',
    historyTab: 'History',
    cashBill: '💵 Cash Bill',
    creditBill: '📋 Credit Bill',
    searchProductPlaceholder: 'Search medicine, cement, or disease...',
    farmerDetails: 'Farmer Information',
    farmerName: 'Farmer Name *',
    fatherName: "Father's Name (Optional)",
    village: 'Village',
    phone: 'Mobile Number (10 digits)',
    cartItems: '🛒 Cart Items',
    emptyCart: 'No items in this bill. Search above or add from Pest Search.',
    emptyBillError: 'Add at least one item to the bill.',
    billItemsLabel: 'Items',
    emptyInvoiceItems: 'No item details are available',
    subtotal: 'Subtotal:',
    discount: 'Discount (₹):',
    grandTotal: 'Grand Total:',
    paid: 'Paid Amount:',
    due: 'Balance Due:',
    saveBill: '🖨 Save & Print Bill (Drive Sync)',
    updateBill: '💾 Update & View Memo',
    availableMedicines: '📦 Available Medicines',
    syncMedicines: '🔄 Sync Medicines',
    singleAdd: '➕ Single',
    bulkAdd: '📦 Bulk Add',
    allPests: 'All',
    lowStockChip: '⚠️ Low Stock',
    oldBills: '📜 Previous Bills History',
    syncHistory: '🔄 Sync History',
    receipt: 'Receipt',
    edit: '✏️ Edit',
    pdf: '🖨️ PDF',
    whatsapp: '💬 WA',
    newBill: '🔄 New Bill',
    change: '✏️ Change',
    outOfStockBadge: '🔴 Out of Stock',
    lowStockBadge: '⚠️ Low Stock',
    dosePerAcreLabel: 'Per Acre',
    drumDoseLabel: '200L Drum',
    pumpDoseLabel: 'Per 15L Pump',
    cementTitle: '🏗️ Cement & Building Materials',
    cementSubtitle: 'All available cement products',
    cementSearchPlaceholder: 'Search brand, company, or grade...',
    cementAllBrands: 'All brands',
    cementLowStockOnly: '⚠️ Low stock only',
    cementSync: 'Sync',
    cementSyncPending: 'Cement is saved locally; database sync is pending.',
    cementAdd: '➕ Add cement',
    cementAddToBill: '➕ Add to bill',
    cementOutOfStock: '🔴 Out of stock',
    cementLowStock: '⚠️ Low stock',
    cementBagStockCount: 'Stock: {count} bags',
    cementBagUnit: 'bag',
    cementInStock: 'bags in stock',
    cementStockAdjustment: 'Adjust stock',
    cementNoItems: 'No cement products found',
    cementEdit: '✏️️ Edit',
    cementDelete: '🗑 Delete',
    cementDeleteTitle: 'Delete cement?',
    cementDeleteMessage: 'Remove "{brand}" from the cement list?',
    cementAddTitle: 'Add cement',
    cementEditTitle: 'Edit cement',
    cementBrand: 'Brand *',
    cementCompany: 'Company *',
    cementGrade: 'Grade *',
    cementBagWeight: 'Bag weight *',
    cementCashPrice: 'Cash price / bag *',
    cementCreditPrice: 'Credit price / bag *',
    cementCashLabel: 'Cash',
    cementCreditLabel: 'Credit',
    cementStockError: 'Only {count} bags are in stock.',
    cementStock: 'Stock (bags) *',
    cementBrandPlaceholder: 'e.g. UltraTech Cement',
    cementCompanyPlaceholder: 'e.g. UltraTech',
    cementBagWeightPlaceholder: 'e.g. 50 kg',
    cementBatchOptional: 'Batch (optional)',
    cementExpiryOptional: 'Expiry (optional)',
    cementRequired: 'This field is required',
    cementInvalidNumber: 'Enter a number zero or greater',
    cementSave: 'Save cement',
    cementSaveChanges: 'Save changes',
    cementAddedToBill: 'Cement added to bill.',
    cementAdded: 'Cement saved to the local list.',
    cementUpdated: 'Cement details updated.',
    cementDeleted: 'Cement removed from the list.'
  }
};

export { STRINGS };